- name: First interaction
  uses: actions/first-interaction@v1.1.1
steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ 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 }}
    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users' first issue.'
    pr-message: 'Message that will be displayed on users' first pr. Look, a `code block` for markdown.'
- name: Deploy Environment
  uses: parasoft/deploy-environment-action@1.0.2
