- name: First interaction
  uses: actions/first-interaction@v1.1.1
steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ 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 }}
    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users' first issue.'
    pr-message: 'Message that will be displayed on users' first pr. Look, a `code block` for markdown.'
    - name: GitHub Actions Workflow Linter
  uses: cschleiden/actions-linter@v1
name: Lint workflows
on:
  pull_request:
    branches:
      - main
      - 'releases/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml"]'
- name: Workflow Toggle
  uses: StephenMP/workflow-toggle@v1.0.0
- name: Toggle Workflow
  uses: StephenMP/workflow-toggle@v1
  with:
    token: ${{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}}
    workflow_id: action.yml
    action: enable
    owner: ah-ha-admin
    repo: La-Grenouille-Qui-Ball
- name: AutML Workflow
  uses: ZoranPandovski/automl-actions@v1.0.2
job_name:
  runs-on: ubuntu-latest
  name: A job to train new model
  steps:
  - name: Train new model
    id: train
    uses: ZoranPandovski/automl-actions@v1.0.0
    with:
      dataset: "home_rentals.csv"
      target: "price"
      when: "{sqft: 500, rooms: 5}"
- name: Workflow trigger
  uses: julianiag/workflow-trigger@v0.1.10
- name: GitHub Runtime
  uses: crazy-max/ghaction-github-runtime@v2.1.0
name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      -
        name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort
