- name: Checkout
  uses: actions/checkout@v3.3.0
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
- name: GitHub Script
  uses: actions/github-script@v6.3.3 
    Github-Token: ${{ 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 }}
    issue-message: '# Message with markdown.\nThis is the message that will be displayed on users' first issue.'
    pr-message: 'Message that will be displayed on users' first pr. Look, a `code block` for markdown.'
    - name: GitHub Actions Workflow Linter
  uses: cschleiden/actions-linter@v1
name: Lint workflows
on:
  pull_request:
    branches:
      - main
      - 'releases/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml"]'
- name: Workflow Toggle
  uses: StephenMP/workflow-toggle@v1.0.0
- name: Toggle Workflow
  uses: StephenMP/workflow-toggle@v1
  with:
    token: ${{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}}
    workflow_id: action.yml
    action: enable
    owner: ah-ha-admin
    repo: La-Grenouille-Qui-Ball
- name: Workflow trigger
  uses: julianiag/workflow-trigger@v0.1.10
- name: GitHub Runtime
  uses: crazy-max/ghaction-github-runtime@v2.1.0
name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      -
        name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort
- name: Setup Node.js environment
  uses: actions/setup-node@v3.6.0
steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
  with:
    node-version: 16
- run: npm ci
- run: npm test
- name: Super-Linter
  uses: github/super-linter@v4.10.0
- name: Configure GitHub Pages
  uses: actions/configure-pages@v2.1.3
- name: Deploy GitHub Pages site
  uses: actions/deploy-pages@v2.0.5
